services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      # In production, tokens are generated dynamically and managed securely.
      - VAULT_DEV_ROOT_TOKEN_ID=root
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      # VAULT_ADDR: This sets the address for clients connecting to Vault.
      - VAULT_ADDR=http://127.0.0.1:8200
    # for production or file/other persistent backends so that it doesn't leak unsealed data, but i added it here for reference 
    cap_add:
      - IPC_LOCK
    command: server -dev -dev-root-token-id=root -dev-listen-address=0.0.0.0:8200