---
- name: Configure Web Application with Vault Secrets
  hosts: webservers
  gather_facts: no

  vars:
    vault_addr: "http://127.0.0.1:8200"
    vault_role_id: "22f97a74-0f09-a78e-0b12-cca76964c00b"
    vault_secret_id: "08665822-944b-b94d-36be-439f3864c10c"

  tasks:
    - name: Authenticate to Vault and retrieve database credentials
      community.hashi_vault.vault_read:
        url: "{{ vault_addr }}"
        auth_method: approle
        role_id: "{{ vault_role_id }}"
        secret_id: "{{ vault_secret_id }}"
        path: "secret/data/my-app/db-creds" # KV v2 path
      register: db_creds_from_vault
      delegate_to: localhost

    - name: Abstract nested Vault data (hide the horror)
      set_fact:
        vault_secret_data: "{{ db_creds_from_vault.data.data.data }}"

    - name: Display retrieved database username
      debug:
        msg: "Database Username: {{ vault_secret_data.username }}"

    - name: Display retrieved database password
      debug:
        msg: "Database Password: {{ vault_secret_data.password }}"
